-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = "markdown",
--   callback = function()
--     vim.opt_local.textwidth = 80
--     vim.opt_local.wrap = true
--     vim.opt_local.linebreak = true
--     vim.opt_local.spell = false
--     vim.bo.formatexpr = ""
--     vim.opt_local.formatoptions:append("t")
--   end,
-- })
--
-- vim.api.nvim_create_autocmd("BufReadPost", {
--   pattern = "*.md",
--   callback = function()
--     vim.opt_local.textwidth = 80
--     vim.bo.formatexpr = ""
--     local row, col = unpack(vim.api.nvim_win_get_cursor(0))
--     vim.cmd("normal! gggqG")
--     vim.api.nvim_win_set_cursor(0, { row, col })
--   end,
-- })
